name: Docker Image r2u/PROJ
on:
  workflow_dispatch: null
  push:
    paths: ['r2u.Dockerfile', '.github/workflows/docker-r2u.yml', 'install_cmake_version_proj.sh']
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        if: github.repository == 'mdsumner/proj-builds'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build the (r2u) Docker image
        if: github.repository == 'mdsumner/proj-builds'
        run: docker build -f r2u.Dockerfile . --tag ghcr.io/mdsumner/proj-builds:r2u
      - name: Publish (r2u)
        if: github.repository == 'mdsumner/proj-builds'
        run: docker push ghcr.io/mdsumner/proj-builds:r2u

