name: Docker Image CI - devel
on:
  workflow_dispatch: null
  push:
    paths: ['dockerfiles/proj_devel.Dockerfile', '.github/workflows/docker-devel.yml', 'install_cmake_version_proj.sh']
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        if: github.repository == 'mdsumner/proj-builds'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build the (devel) Docker image
        if: github.repository == 'mdsumner/proj-builds'
        run: docker build -f dockerfiles/proj_devel.Dockerfile . --tag ghcr.io/mdsumner/proj-builds:devel
      - name: Publish (devel)
        if: github.repository == 'mdsumner/proj-builds'
        run: docker push ghcr.io/mdsumner/proj-builds:devel

