name: Docker Image CI - 8.2.0
on:
  workflow_dispatch: null
  push:
    paths: ['proj_8.2.0.Dockerfile', '.github/workflows/docker-8.2.0.yml', 'install_cmake_version_proj.sh']
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        if: github.repository == 'mdsumner/proj-builds'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build the (8.2.0) Docker image
        if: github.repository == 'mdsumner/proj-builds'
        run: docker build -f proj_8.2.0.Dockerfile . --tag ghcr.io/mdsumner/proj-builds:8.2.0
      - name: Publish (8.2.0)
        if: github.repository == 'mdsumner/proj-builds'
        run: docker push ghcr.io/mdsumner/proj-builds:8.2.0

