name: Docker Image CI - 7.1.1
on:
  workflow_dispatch: null
  push:
    paths: ['proj_7.1.1.Dockerfile', '.github/workflows/docker-7.1.1.yml', 'install_cmake_version_proj.sh']
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        if: github.repository == 'mdsumner/proj-builds'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build the (7.1.1) Docker image
        if: github.repository == 'mdsumner/proj-builds'
        run: docker build -f proj_7.1.1.Dockerfile . --tag ghcr.io/mdsumner/proj-builds:7.1.1
      - name: Publish (7.1.1)
        if: github.repository == 'mdsumner/proj-builds'
        run: docker push ghcr.io/mdsumner/proj-builds:7.1.1

