name: Docker Image CI - devel (latest commit)
on:
  workflow_dispatch: null
  push:
    paths: ['Dockerfile', '.github/workflows/docker-devel.yml', 'install_version_proj.sh']
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        if: github.repository == 'mdsumner/proj-builds'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build the (trunk, latest commit) Docker image
        if: github.repository == 'mdsumner/proj-builds'
        run: docker build . --tag ghcr.io/mdsumner/proj-builds:master
      - name: Publish (master)
        if: github.repository == 'mdsumner/proj-builds'
        run: docker push ghcr.io/mdsumner/proj-builds:master
