name: Docker Image CI - 9.0.0
on:
  workflow_dispatch: null
  push:
    paths: ['dockerfiles/proj_9.0.0.Dockerfile', '.github/workflows/docker-9.0.0.yml', 'install_cmake_version_proj.sh']
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        if: github.repository == 'mdsumner/proj-builds'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build the (9.0.0) Docker image
        if: github.repository == 'mdsumner/proj-builds'
        run: docker build -f dockerfiles/proj_9.0.0.Dockerfile . --tag ghcr.io/mdsumner/proj-builds:9.0.0
      - name: Publish (9.0.0)
        if: github.repository == 'mdsumner/proj-builds'
        run: docker push ghcr.io/mdsumner/proj-builds:9.0.0

